# Generated by Django 4.2.4 on 2023-08-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='conpany_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
