# Generated by Django 4.2.4 on 2023-08-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_conpany_name_entry_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
