# Generated by Django 4.2.4 on 2023-08-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_entry_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
