# Generated by Django 4.2.4 on 2023-08-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_entry_platform_entry_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='cemail',
            new_name='designation',
        ),
    ]
